### ISSUE TITLE
Cannot detach fairings

### ISSUE THREAD

**Issue by Maxzhao1999** [rsparkyc/ProceduralFairings#1]
I seem to be having a problem where the button for detaching fairings have disappeared. I'm using v4.0 with KSP 1.3.1

**Comment by rsparkyc** [comment]
can you see if it works properly with KSP 1.3.0?  I haven't tried with 1.3.1

**Comment by Maxzhao1999** [comment]
I used to play 1.3.0 with procedural fairings and I'm fairly certain it works flawless. I'm trying to test a bit more now

**Comment by Maxzhao1999** [comment]
Just realised I used the fuselage fairings instead of the payload fairings. Can confirm that Procedural fairings work flawlessly in 1.3.1
