### ISSUE TITLE
NullReferenceException spam caused by attaching an interstage adaptor to an engine that has a shroud.

### ISSUE THREAD

**Issue by BasharMilesTeg** [rsparkyc/ProceduralFairings#5]
For KSP v1.4.3.2152; PF v1.4.3.2
When the top node of an interstage adaptor 'KzInterstageAdapter2' is attached to an engine that has a shroud ([Spark](https://wiki.kerbalspaceprogram.com/wiki/48-7S_%22Spark%22_Liquid_Fuel_Engine)) a NRE repeats until the engine is deleted.
>NullReferenceException: Object reference not set to an instance of an object
>  at ModuleJettison.FetchActiveMeshTransform (System.String nameList) [0x00000] in <filename unknown>:0 
>  at ModuleJettison.LateUpdate () [0x00000] in <filename unknown>:0 

This doesn't occur if the engine doesn't have a shroud ([Ant](https://wiki.kerbalspaceprogram.com/wiki/LV-1_%22Ant%22_Liquid_Fuel_Engine))

![image](https://user-images.githubusercontent.com/10259776/40733189-a535615e-6467-11e8-91a1-ea3bcb5cb01d.png)

**Comment by rsparkyc** [comment]
Should be fixed here: https://github.com/rsparkyc/ProceduralFairings/releases/tag/1.4.3.4

You'll need to manually disable the fairing from the engine, but I think that's a lot better than spamming the logs with exceptions.  I wanted to figure out how I could access that field with code, but it didn't seem to be working.
